name: Docker Build and Delpoy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3
        with:
          buildx-version: latest
          qemu-version: latest
      - name: Login in DockerHub
        if: github.event_name 1= 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: app/
          file: app/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
          push: ${{ github.event_name != 'pull_request' }}

deploy:
  needs: build
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: Install Helm
      with:
        version: v3.7.2
      - name: Configure kubectl
        uses: azure/configure-kubectl@v1
        with:
          configuration: '${{ secrets.KUBECONFIG }}'
      - name: Deploy to Kubernetes
        run: |
          helm upgrade --install app ./helm --set deployment.image=${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:latest
